// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgnIKz6A-DbI5k5pYdGuRi4uAUqKamPRE',
    appId: '1:797960223311:web:b37d75ee922ce11f3a883a',
    messagingSenderId: '797960223311',
    projectId: 'game-discovery-app-1441e',
    authDomain: 'game-discovery-app-1441e.firebaseapp.com',
    storageBucket: 'game-discovery-app-1441e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdU-7MTshoPtHcDyuAfvMhPqszO7w1fJs',
    appId: '1:797960223311:android:23ade394ff28630d3a883a',
    messagingSenderId: '797960223311',
    projectId: 'game-discovery-app-1441e',
    storageBucket: 'game-discovery-app-1441e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo20X_4ulzr9dgoKcUDsljLTHECCwgLgM',
    appId: '1:797960223311:ios:b740042555b3c0b73a883a',
    messagingSenderId: '797960223311',
    projectId: 'game-discovery-app-1441e',
    storageBucket: 'game-discovery-app-1441e.firebasestorage.app',
    iosBundleId: 'com.example.gameDiscoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo20X_4ulzr9dgoKcUDsljLTHECCwgLgM',
    appId: '1:797960223311:ios:b740042555b3c0b73a883a',
    messagingSenderId: '797960223311',
    projectId: 'game-discovery-app-1441e',
    storageBucket: 'game-discovery-app-1441e.firebasestorage.app',
    iosBundleId: 'com.example.gameDiscoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgnIKz6A-DbI5k5pYdGuRi4uAUqKamPRE',
    appId: '1:797960223311:web:1b455415b772155e3a883a',
    messagingSenderId: '797960223311',
    projectId: 'game-discovery-app-1441e',
    authDomain: 'game-discovery-app-1441e.firebaseapp.com',
    storageBucket: 'game-discovery-app-1441e.firebasestorage.app',
  );
}
